[package]
name = "qr"
version = "0.1.0"
edition = "2021"
publish = false

[lib]

[dependencies]
poem = { version ="1.3.55",features = ["static-files"]}
poem-openapi = { version = "2", features = ["swagger-ui"]}
image = "0.24.5"
rqrr = "0.6.0"
shuttle-static-folder = "0.11.0"
anyhow = "1.0.69"
shuttle-secrets = "0.11.0"
shuttle-service = { version = "0.11.0", features = ["web-poem"] }
tracing = "0.1.37"
serde = {version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
reqwest = { version = "0.11.14", features = ["json", "multipart", "stream", "gzip", "deflate", "brotli"] }
lazy_static = "1.4.0"
json = "0.12.4"
tokio = "1.22"
regex = "1.7.1"
