[package]
name = "qr"
version = "0.1.0"
edition = "2021"
publish = false

[lib]

[dependencies]
shuttle-service = { version = "0.10.0", features = ["web-poem"] }
poem = { version ="1.3.54",features = ["static-files"]}
image = "0.24.5"
rqrr = "0.6.0"
shuttle-static-folder = "0.10.0"
